name: Actionlint

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/**"
  pull_request:
    paths:
      - ".github/workflows/**"

jobs:
  actionlint:
    uses: tksst/github-actions-workflows/.github/workflows/actionlint.yml@dad9814cc9c69d48020962b0e2aaa89e4b48f796
