name: Test and Release
on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml
  release:
    needs: test
    permissions:
      # create a PR
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: set up the project
        uses: tksst/github-actions-workflows/actions/setup-pnpm-project@118c76c1845aa9c8974dd0664742f4c46ed25304
        with:
          node-version: 18

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@f13b1baaa620fde937751f5d2c3572b9da32af23 # v1.4.5
        with:
          publish: pnpm exec changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
