name: Test and Release
on:
  push:
    branches:
      - master
      - alpha

jobs:
  test:
    uses: ./.github/workflows/test.yml
  release:
    needs: test
    permissions:
      issues: write
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
        with:
          # fetch all history
          fetch-depth: 0

      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: 18
          cache: npm

      - name: Enable corepack
        run: corepack enable npm

      - name: Print npm version
        run: npm --version

      - run: npm ci

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
