name: Lint

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - main

jobs:
  check-skippable:
    continue-on-error: true
    runs-on: ubuntu-24.04
    permissions:
      actions: write
      contents: read
    timeout-minutes: 10
    outputs:
      skippable: ${{ steps.check.outputs.should_skip }}
    steps:
      - id: check
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5.3.1

  lint:
    name: Lint
    needs: check-skippable
    if: needs.check-skippable.outputs.skippable != 'true'
    permissions:
      contents: read
      actions: read
    timeout-minutes: 10

    # Using matrix strategy, OS and Node version will be displayed in a title of a job.
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        node-version:
          # oldest LTS
          - 18

    runs-on: ${{ matrix.os }}

    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@94c3c3d9567a0205de6da68a76c428ce4e769af1 # v2.0.0
        continue-on-error: true
        with:
          # Set to true to publish the results as comment to the PR (applicable if workflow run is triggered by PR).
          comment_on_pr: false

      - name: Checkout the source
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          show-progress: false
          submodules: recursive

      - name: Setup pnpm
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
        with:
          standalone: false

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm lint

  action-timeline:
    needs:
      - check-skippable
      - lint
    # Runs even when the previous job was in error
    if: ${{ always() }}
    continue-on-error: true
    runs-on: ubuntu-24.04
    permissions:
      actions: read
    timeout-minutes: 10
    steps:
      - uses: Kesin11/actions-timeline@b03a6aa289adef5534c84ccb6fbef7c975973574 # v2.1.0
