name: Lint

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - main
      - alpha

jobs:
  lint:
    name: Lint
    uses: tksst/github-actions-workflows/.github/workflows/nodejs-pnpm.yml@4519d724fd3e9b0295f9407d5b48f019d1d43033
    with:
      os: '["ubuntu-latest"]'
      node-versions: "[18]"
      pnpm-commands: '["lint"]'
      job-title: Lint
