name: Lint

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check whether it can skip
        id: check-skippable
        continue-on-error: true
        uses: fkirc/skip-duplicate-actions@12aca0a884f6137d619d6a8a09fcc3406ced5281 # v5.3.0

      - name: set up the project
        if: steps.check-skippable.outputs.should_skip != 'true'
        uses: tksst/github-actions-workflows/actions/setup-pnpm-project@118c76c1845aa9c8974dd0664742f4c46ed25304

      - if: steps.check-skippable.outputs.should_skip != 'true'
        run: pnpm lint
