name: Lint

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - master
      - alpha

jobs:
  lint:
    name: Lint
    uses: tksst/github-actions-workflows/.github/workflows/nodejs-pnpm.yml@dad9814cc9c69d48020962b0e2aaa89e4b48f796
    with:
      build: false
      test: false
      os: '["ubuntu-latest"]'
      node-versions: "[18]"
